workspace = { members = ["solution_1", "solution_2540", "solution_349", "solution_383"] }
[package]
name = "leetcode_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solution_1 = { path = "solution_1" }
solution_349 = { path = "solution_349" }
solution_2540 = { path = "solution_2540" }
